### Numpy

In [1]:
import numpy as np

In [3]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [5]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

axis là tham số chỉ định chiều dọc hay chiều ngang mà một thao tác sẽ được thực hiện
- axis = 0 : thực hiện theo hàng
- axis = 1: thực hiện theo cột

Mỗi chiều thì được gọi là một axis
Số lượng axis được gọi là rank



### shape


shape cho biết kích thước (số chiều) của một mảng 
shape trả về một tuple:
- số phần tử trong tuple: số chiều
- giá trị trong tuple : số phần tử dọc theo từng chiều

size của array chính bằng tổng số lượng phần tử có trong mảng đó

In [6]:
b.shape

(3, 4)

In [7]:
b.size

12

In [9]:
b.ndim   # bằng với len(a.shape)

2

## N-dimensional arrays

In [10]:
a = np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
a.shape

(2, 3, 4)

In [12]:
type(a)

numpy.ndarray

In [14]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [16]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

tạo một mảng với kích thước và giá trị cho trước

In [17]:
a = np.full((3,4), np.pi)
a

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

tạo một mảng rỗng (các giá trị bên trong sẽ bất cứ điều gì ở trong bộ nhớ trước đó)

In [19]:
c = np.empty((3,4))
c

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

tạo một một chứa các giá trị trong một khoảng

In [21]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [22]:
a = np.arange(1.0, 6.0)
a

array([1., 2., 3., 4., 5.])

có thể thêm một tham số khoảng cách giữa các phần tử


In [23]:
a = np.arange(1,10,2 )
a

array([1, 3, 5, 7, 9])

tạo một mảng với số lượng phần tử cho trước trong 1 khoảng

In [ ]:
a = np.linspace(-2,2,500)  # tạo 500 phần tử cách đều có giá trị trong khoảng từ -2 đến 2
a

array([-2.        , -1.99198397, -1.98396794, -1.9759519 , -1.96793587,
       -1.95991984, -1.95190381, -1.94388778, -1.93587174, -1.92785571,
       -1.91983968, -1.91182365, -1.90380762, -1.89579158, -1.88777555,
       -1.87975952, -1.87174349, -1.86372745, -1.85571142, -1.84769539,
       -1.83967936, -1.83166333, -1.82364729, -1.81563126, -1.80761523,
       -1.7995992 , -1.79158317, -1.78356713, -1.7755511 , -1.76753507,
       -1.75951904, -1.75150301, -1.74348697, -1.73547094, -1.72745491,
       -1.71943888, -1.71142285, -1.70340681, -1.69539078, -1.68737475,
       -1.67935872, -1.67134269, -1.66332665, -1.65531062, -1.64729459,
       -1.63927856, -1.63126253, -1.62324649, -1.61523046, -1.60721443,
       -1.5991984 , -1.59118236, -1.58316633, -1.5751503 , -1.56713427,
       -1.55911824, -1.5511022 , -1.54308617, -1.53507014, -1.52705411,
       -1.51903808, -1.51102204, -1.50300601, -1.49498998, -1.48697395,
       -1.47895792, -1.47094188, -1.46292585, -1.45490982, -1.44

tạo một mảng nhiều chiều với giá trị ngẫu nhiên bằng random

In [ ]:
# khởi tạo các giá trị ngẫu nhiên trong khoảng từ 0 đến 1 (phân phối đều)
a = np.random.rand(3,4)
a

array([[0.39971673, 0.63498324, 0.17056965, 0.41259306],
       [0.00528452, 0.81667419, 0.25773667, 0.17962827],
       [0.7939285 , 0.83791895, 0.24337961, 0.9664591 ]])

In [25]:
# khởi tạo các giá trị ngẫu nhiên theo phân phối chuẩn
# với độ lệch chuẩn = 1 và trung bình bằng 0
a = np.random.randn(3,4)
a

array([[ 0.18288674,  1.89881739, -2.61833205, -0.61642543],
       [ 1.32818946, -0.56995882,  0.44137459, -0.76846949],
       [-0.64347203,  0.06805928,  0.6443783 , -1.38493433]])

Dùng dtype để biết kiểu dữ liệu trong array

In [26]:
a = np.full((3,4), 32)
print(a.dtype, a)

int32 [[32 32 32 32]
 [32 32 32 32]
 [32 32 32 32]]


chúng ta có thể khởi tạo sẵn kiểu dữ liệu cho array

In [28]:
a = np.full((3,4), 32, dtype = np.float64)
a

array([[32., 32., 32., 32.],
       [32., 32., 32., 32.],
       [32., 32., 32., 32.]])

## Reshaping an array

Ta có thể reshape của một array ngay tại chỗ, tuy nhiên vẫn phải giữ nguyên size

In [29]:
g = np.arange(24)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
g.shape = (6,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
g.shape = (2,3,4)
g

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Ta có thể dùng hàm reshape để thay đổi hình dạng của mảng. tuy nhiên hàm này sẽ tạo ra một đối tượng array mới chỉ vào cùng 1 đối tượng. 
Có nghĩa là nếu sửa đổi một mảng cũng sẽ sửa đổi cái kia

In [33]:
g2 = g.reshape(4,6)
g2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [35]:
g2[1,2] = 999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [36]:
g

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

## Arithmetic operations

In [38]:
a =np.array([14,23,32,41])
b = np.array([5,4,3,2])


In [39]:
a

array([14, 23, 32, 41])

In [40]:
b

array([5, 4, 3, 2])

In [41]:
print(a+b)

[19 27 35 43]


In [42]:
a - b

array([ 9, 19, 29, 39])

In [43]:
a * b

array([70, 92, 96, 82])

In [44]:
a / b

array([ 2.8       ,  5.75      , 10.66666667, 20.5       ])

In [45]:
a // b

array([ 2,  5, 10, 20])

In [46]:
a % b

array([4, 3, 2, 1])

In [47]:
a ** b

array([537824, 279841,  32768,   1681])

Lưu ý rằng khi thực hiện các phép toán, hai mảng phải có hình dạng như nhau

Nếu không thì numpy sẽ áp dụng broadcasting

## Broadcasting

là quá trình tự động mở rộng kích thước của mảng nhỏ hơn để khớp  với mảng lớn hơn khi thực hiện các phép toán

### First rule

Nếu hai mảng có số chiều khác nhau, mảng có ít chiều hơn sẽ được mở rộng thêm chiều về phía trước

In [48]:
h = np.array([[[0, 1, 2, 3, 4]]])
h

array([[[0, 1, 2, 3, 4]]])

In [49]:
h + [10, 20, 30, 40, 50]  # same as: h + [[[10, 20, 30, 40, 50]]]

array([[[10, 21, 32, 43, 54]]])

mảng [10,20,30,40,50] được mở rộng thành (1,3) để cộng với h

### Second rule

Hai chiều tương ứng phải bằng nhau hoặc một trong hai bằng 1

In [50]:
k = np.array([[0, 1, 2],
       [3, 4, 5]])
k   # shape (2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
k + [[100], [200]]  # same as: k + [[100, 100, 100], [200, 200, 200]]

array([[100, 101, 102],
       [203, 204, 205]])

### Third rule

Nếu không thoả mãn quy tắc một hoặc hai => lỗi

### Upcasting

Là quá trình tự động chuyển đổi kiểu dữ liệu (dtype) nhỏ hơn thành kiểu lớn hơn khi thực hiện phép toán để tránh mất mát dữ liệu

In [52]:
k1 = np.arange(0,5, dtype=np.int32)
k1.dtype

dtype('int32')

In [55]:
k2 = np.arange(6,11, dtype= np.int64)
k2.dtype

dtype('int64')

In [57]:
k3 = k1 + k2
k3

array([ 6,  8, 10, 12, 14], dtype=int64)

## Condition operators

In [58]:
m = np.array([20,-5,30,40])
m < [15,16,35,36]

array([False,  True,  True, False])

In [59]:
m < 25

array([ True,  True, False, False])

In [60]:
m[m<25]

array([20, -5])

## Mathematical and statistical functions

In [61]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])

In [62]:
a

array([[-2.5,  3.1,  7. ],
       [10. , 11. , 12. ]])

In [63]:
a.mean()

6.766666666666667

In [64]:
a.min()

-2.5

In [65]:
a.max()

12.0

In [66]:
a.sum()

40.6

In [68]:
# tính tích của tất cả các phần tử
a.prod()

-71610.0

In [69]:
# tính độ lệch chuẩn của tất cả các phần tử
a.std()

5.084835843520964

In [70]:
a.var()

25.855555555555554

sử dụng các phương thức với tham số axis

In [71]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# tổng tất cả các phần tử
c.sum(axis = None)

276

In [ ]:
# tính tổng theo hàng
c.sum(axis = 0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [74]:
# tính tổng theo cột
c.sum(axis = 1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [75]:
# tính tổng qua nhiều trục
c.sum(axis =(0,1))

array([60, 66, 72, 78])

## Các hàm hoạt động trên từng phần tử của mảng

In [76]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
a

array([[-2.5,  3.1,  7. ],
       [10. , 11. , 12. ]])

In [77]:
np.square(a)

array([[  6.25,   9.61,  49.  ],
       [100.  , 121.  , 144.  ]])

In [79]:
np.abs(a)

array([[ 2.5,  3.1,  7. ],
       [10. , 11. , 12. ]])

In [80]:
np.sqrt(a)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12748\2835837605.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([[       nan, 1.76068169, 2.64575131],
       [3.16227766, 3.31662479, 3.46410162]])

In [81]:
# tính hàm mũ cơ số e (e^...)
np.exp(a)

array([[8.20849986e-02, 2.21979513e+01, 1.09663316e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [82]:
np.log(a)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12748\176755284.py:1: RuntimeWarning: invalid value encountered in log
  np.log(a)


array([[       nan, 1.13140211, 1.94591015],
       [2.30258509, 2.39789527, 2.48490665]])

In [84]:
# làm tròn lên số nguyên gần nhất
np.ceil(a)

array([[-2.,  4.,  7.],
       [10., 11., 12.]])

In [85]:
# tách phần thập phân và phần nguyên của từng phần tử
np.modf(a)

(array([[-0.5,  0.1,  0. ],
        [ 0. ,  0. ,  0. ]]),
 array([[-2.,  3.,  7.],
        [10., 11., 12.]]))

In [86]:
# kiểm tra NaN
np.isnan(a)

array([[False, False, False],
       [False, False, False]])

## Array Indexing

cú pháp: list[start:stop:step]

In [87]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

19

In [88]:
a[2:5]

array([ 3, 19, 13])

In [89]:
a[2:-1]

array([ 3, 19, 13,  7])

In [91]:
a[2::2]

array([ 3, 13,  3])

In [92]:
a[::]

array([ 1,  5,  3, 19, 13,  7,  3])

In [93]:
a[:]

array([ 1,  5,  3, 19, 13,  7,  3])

In [94]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

có thể sửa một hoặc nhiều phần tử trong array

In [95]:
a[3] = 999
a

array([  1,   5,   3, 999,  13,   7,   3])

In [96]:
a[2:5] = [997, 998,999]
a

array([  1,   5, 997, 998, 999,   7,   3])

nếu như bạn tạo một slices từ array và thực hiện thay đổi trên slices đó, data gốc cũng sẽ thay đổi

In [97]:
a_slices = a[2:6]
a_slices

array([997, 998, 999,   7])

In [98]:
a_slices[1] = 1000
a

array([   1,    5,  997, 1000,  999,    7,    3])

sử dụng copy() để không ảnh hưởng đến dữ liệu gốc

In [99]:
a

array([   1,    5,  997, 1000,  999,    7,    3])

In [ ]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a     # a không bị ảnh hưởng

array([   1,    5,  997, 1000,  999,    7,    3])

### Index trong mảng nhiều chiều

In [101]:
b = np.arange(48).reshape(4,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [102]:
b[1,2]   # hàng 1 cột 2

14

In [103]:
b[1,:] # hàng 1 và toàn bộ cột

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [104]:
b[(0,2), 2:5] # hàng 0 và 2, cột từ 2 đến 4

array([[ 2,  3,  4],
       [26, 27, 28]])

In [105]:
b[:,(-1,2,-1)] # tất cả các hàng, cột cuối, cột 2 và cột cuối

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

In [106]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)]  # returns a 1D array with b[-1, 5], b[2, 9], b[-1, 1] and b[2, 9] (again)

array([41, 33, 37, 33])

## Higher dimensions

In [107]:
c = b.reshape(4,2,6)
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [108]:
c[2,1,4]

34

In [109]:
c[2,:,3]

array([27, 33])

In [110]:
c[2,1,:]

array([30, 31, 32, 33, 34, 35])

## Stacking arrays

stacking arrays là thao tác kết hợp nhiều mảng lại với nhau dọc theo các chiều khác nhau! Nó cực kỳ hữu ích khi bạn làm việc với dữ liệu nhiều chiều.

In [111]:
q1 = np.full((3,4),1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [112]:
q2 = np.full((4,4),2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [113]:
q3 = np.full((3,4),3.0)
q3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [114]:
# kết hợp các mảng thẳng theo chiều thẳng đứng
q4 = np.vstack((q1,q2,q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [116]:
# kết hợp các mảng theo chiều ngang
q5 = np.hstack((q1,q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [117]:
# xếp các mảng theo một trục mới:
q6 = np.stack((q1,q3))
q6

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [118]:
q6.shape

(2, 3, 4)

## Splitting array

In [119]:
r = np.arange(24).reshape(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [120]:
# chia mảng thành 3 phần theo chiều thẳng đứng
r1, r2,r3 = np.vsplit(r,3)
r1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [121]:
r2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
r3

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [123]:
# chia mảng thành 2 phần theo chiều ngang
r4, r5 = np.hsplit(r,2)
r4

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [124]:
r5

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

## Linear algebra

In [125]:
m1 = np.arange(10).reshape(2,5)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [126]:
# ma trận chuyển vị
m1.T


array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [127]:
# nhân 2 ma trận
n1 = np.arange(10).reshape(2, 5)
n2 = np.arange(15).reshape(5,3)
n1.dot(n2)

array([[ 90, 100, 110],
       [240, 275, 310]])

In [128]:
m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [129]:
# tính ma trận khả nghịch của một ma trận vuông
import numpy.linalg as linalg
linalg.inv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

 Pseudo-invers là một dạng nghịch đảo tổng quát giúp giải các hệ phương trình tuyến tính ngay cả khi:
- Ma trận không vuông (số hàng khác số cột).
- Ma trận suy biến (det(A) = 0, không thể nghịch đảo thông thường).

In [130]:
linalg.pinv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

In [131]:
# phép nhân ma trận giữa 1 ma trận và nghịch đảo của nó trả về một ma trận đơn vị
m3.dot(linalg.inv(m3))

array([[ 1.00000000e+00, -1.66533454e-16,  0.00000000e+00],
       [ 6.31439345e-16,  1.00000000e+00, -1.38777878e-16],
       [ 5.21110932e-15, -2.38697950e-15,  1.00000000e+00]])

In [132]:
# tạo ma trận đơn vị
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

QR decomposition (phân rã QR) là một kỹ thuật trong đại số tuyến tính giúp phân tách một ma trận thành tích của ma trận trực giao và ma trận tam giác trên.

In [133]:
q ,r = linalg.qr(m3)
q

array([[-0.04627448,  0.98786672,  0.14824986],
       [-0.23137241,  0.13377362, -0.96362411],
       [-0.97176411, -0.07889213,  0.22237479]])

In [134]:
r

array([[-21.61018278, -29.89331494, -32.80860727],
       [  0.        ,   0.62427688,   1.9894538 ],
       [  0.        ,   0.        ,  -3.26149699]])

In [135]:
q.dot(r)

array([[ 1.,  2.,  3.],
       [ 5.,  7., 11.],
       [21., 29., 31.]])

In [136]:
# tính định thức của một ma trận
linalg.det(m3)

43.99999999999997

In [137]:
# tính giá trị riêng và vector riêng của một ma trận
eigenvalues, eigenvectors = linalg.eig(m3)


In [138]:
eigenvalues # λ

array([42.26600592, -0.35798416, -2.90802176])

In [139]:
eigenvectors # v

array([[-0.08381182, -0.76283526, -0.18913107],
       [-0.3075286 ,  0.64133975, -0.6853186 ],
       [-0.94784057, -0.08225377,  0.70325518]])

In [140]:
# trả về giá trị trên đường chéo chính
np.diag(m3)

array([ 1,  7, 31])

In [141]:
# trả về trace ( tổng các phần tử trên đường chéo chính)
m3.trace()

39

### Vectorization

VD bằng tính phép tính sin(x.y/40.5) trong một array 768x1024

In [142]:
# meshgrid nhận vào 2 hoặc nhiều vector
# trả về các ma trận 2D tương ứng:
# X chứa bản sao của các giá trị trên trục x
# Y chứa bản sao của các  giá trị trên trục y
x_coords = np.arange(0, 1024)  # [0, 1, 2, ..., 1023]
y_coords = np.arange(0, 768)   # [0, 1, 2, ..., 767]
X , Y = np.meshgrid(x_coords, y_coords)
X

array([[   0,    1,    2, ..., 1021, 1022, 1023],
       [   0,    1,    2, ..., 1021, 1022, 1023],
       [   0,    1,    2, ..., 1021, 1022, 1023],
       ...,
       [   0,    1,    2, ..., 1021, 1022, 1023],
       [   0,    1,    2, ..., 1021, 1022, 1023],
       [   0,    1,    2, ..., 1021, 1022, 1023]])

In [143]:
Y

array([[  0,   0,   0, ...,   0,   0,   0],
       [  1,   1,   1, ...,   1,   1,   1],
       [  2,   2,   2, ...,   2,   2,   2],
       ...,
       [765, 765, 765, ..., 765, 765, 765],
       [766, 766, 766, ..., 766, 766, 766],
       [767, 767, 767, ..., 767, 767, 767]])

In [146]:
data = np.sin(X * Y / 40.5)
data

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.02468885, 0.04936265, ..., 0.07705885, 0.1016508 ,
        0.12618078],
       [0.        , 0.04936265, 0.09860494, ..., 0.15365943, 0.20224852,
        0.25034449],
       ...,
       [0.        , 0.03932283, 0.07858482, ..., 0.6301488 , 0.59912825,
        0.56718092],
       [0.        , 0.06398059, 0.12769901, ..., 0.56844086, 0.51463783,
        0.45872596],
       [0.        , 0.08859936, 0.17650185, ..., 0.50335246, 0.42481591,
        0.34293805]])

## Saving and loading

In [148]:
a = np.random.rand(2,3)
a

array([[0.72329382, 0.85958652, 0.83734418],
       [0.21009151, 0.52264787, 0.51968887]])

In [149]:
# lưu mảng với binary format
np.save("my_array",a)

In [ ]:
# load một file định dạng nhị phân
loaded = np.load("my_array.npy")
loaded

array([[0.72329382, 0.85958652, 0.83734418],
       [0.21009151, 0.52264787, 0.51968887]])

In [151]:
# lưu mảng với text format
np.savetxt("my_array.csv",a)

In [152]:
# load một file với định dạng text:
loaded2 = np.loadtxt("my_array.csv")
loaded2

array([[0.72329382, 0.85958652, 0.83734418],
       [0.21009151, 0.52264787, 0.51968887]])